<a href="https://colab.research.google.com/github/armancodes1/a-data-science-journey/blob/main/1-Tools/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

NumPy is the fundamental package for **scientific computing** in Python. It provides support for arrays, matrices, linear algebra, random numbers, and more.

## Getting Started

In [ ]:
import numpy as np

## Creating Arrays

In [ ]:
a = np.array([1, 2, 3])
print("1D array:", a)

b = np.array([[1,2,3],[4,5,6]])
print("2D array:\n", b)

1D array: [1 2 3]
2D array:
 [[1 2 3]
 [4 5 6]]


## Array Attributes

In [ ]:
print("Shape:", b.shape)
print("Dimensions:", b.ndim)
print("Data type:", b.dtype)
print("Size:", b.size)

Shape: (2, 3)
Dimensions: 2
Data type: int64
Size: 6


## Special Arrays

In [ ]:
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.eye(3))
print(np.arange(0,10,2))
print(np.linspace(0,1,5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## Indexing and Slicing

In [ ]:
arr = np.arange(10)
print(arr)
print("First element:", arr[0])
print("Slice 2:5:", arr[2:5])
print("Last 3 elements:", arr[-3:])

[0 1 2 3 4 5 6 7 8 9]
First element: 0
Slice 2:5: [2 3 4]
Last 3 elements: [7 8 9]


## Boolean Indexing

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[arr > 3])

[4 5 6]


## Array Operations

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print("Addition:", x+y)
print("Multiplication:", x*y)
print("Dot product:", np.dot(x,y))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot product: 32


## Broadcasting

In [ ]:
m = np.ones((3,3))
print(m + np.array([1,2,3]))

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


## Linear Algebra

In [ ]:
M = np.array([[1,2],[3,4]])
print("Matrix:")
print(M)
print("Determinant:", np.linalg.det(M))
print("Inverse:")
print(np.linalg.inv(M))
print("Eigenvalues:", np.linalg.eig(M)[0])

Matrix:
[[1 2]
 [3 4]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]


## Random Numbers

In [ ]:
np.random.seed(0)
print(np.random.rand(3))
print(np.random.randint(0,10,(3,3)))

[0.5488135  0.71518937 0.60276338]
[[3 7 9]
 [3 5 2]
 [4 7 6]]


> Tip: Use `np.random.seed(0)` at the top of a notebook section to make results reproducible.