# SciPy

SciPy is a Python library for **scientific computing**.

It builds on NumPy and provides tools for **linear algebra, integration, optimization, statistics, and more**.

## Getting Started

In [1]:
import numpy as np
from scipy import linalg, integrate, optimize

## Linear Algebra

In [2]:
A = np.array([[3,2],[1,4]])
B = np.array([5,6])

# Solve Ax = B
x = linalg.solve(A, B)
x

array([0.8, 1.3])

In [3]:
np.allclose(A @ x, B)

True

In [4]:
# Determinant and Inverse
det = linalg.det(A)
inv = linalg.inv(A)
det, inv

(np.float64(10.0),
 array([[ 0.4, -0.2],
        [-0.1,  0.3]]))

In [5]:
# Eigenvalues and Eigenvectors
w, v = linalg.eig(A)
w, v

(array([2.+0.j, 5.+0.j]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

## Integration

In [6]:
# Single integral
res, err = integrate.quad(lambda x: np.exp(-x**2), -np.inf, np.inf)
res

1.7724538509055159

In [7]:
# Double integral
f = lambda y, x: x*y**2
res, err = integrate.dblquad(f, 0, 2, lambda x: 0, lambda x: 1)
res

0.6666666666666667

In [8]:
# ODE solving
def model(y, t):
    return -2*y

t = np.linspace(0, 5, 100)
y0 = 1
sol = integrate.odeint(model, y0, t)
sol[:5]

array([[1.        ],
       [0.90392393],
       [0.81707844],
       [0.7385767 ],
       [0.66761716]])

## Optimization

In [9]:
# Scalar minimization
f = lambda x: (x-2)**2 + 1
res = optimize.minimize_scalar(f)
res

 message: 
          Optimization terminated successfully;
          The returned value satisfies the termination criteria
          (using xtol = 1.48e-08 )
 success: True
     fun: 1.0
       x: 1.9999999999999998
     nit: 4
    nfev: 8

In [10]:
# Multivariable optimization
def f(v):
    x, y = v
    return (x-1)**2 + (y-2.5)**2

res = optimize.minimize(f, [2,0])
res

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 1.0075886140706989e-15
        x: [ 1.000e+00  2.500e+00]
      nit: 2
      jac: [-4.858e-08  1.471e-08]
 hess_inv: [[ 9.310e-01  1.724e-01]
            [ 1.724e-01  5.690e-01]]
     nfev: 9
     njev: 3

In [11]:
# Root finding
f = lambda x: x**3 - 2*x - 5
root = optimize.root_scalar(f, bracket=[2,3])
root.root

2.094551481542327

# **Fin.**