# TensorFlow
---
TensorFlow is an open-source library for **machine learning** and **deep learning**.

 It provides tools for building and training models at scale.

## 1. Setup & Import

In [2]:
# !pip install tensorflow
import tensorflow as tf
print('TensorFlow version:', tf.__version__)

TensorFlow version: 2.19.0


## 2. Tensors
Tensors are the core data structure in TensorFlow (multi-dimensional arrays).

In [3]:
a = tf.constant([[1,2],[3,4]])
print('Tensor a:', a)
print('Shape:', a.shape)
print('Datatype:', a.dtype)

# Tensor operations
b = tf.constant([[5,6],[7,8]])
print('Addition:\n', tf.add(a, b))
print('Multiplication:\n', tf.matmul(a, b))

Tensor a: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Shape: (2, 2)
Datatype: <dtype: 'int32'>
Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## 3. Automatic Differentiation with `GradientTape`
TensorFlow automatically computes gradients for optimization.

In [4]:
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**2 + 2*x + 1

grad = tape.gradient(y, x)
print('dy/dx at x=3:', grad.numpy())

dy/dx at x=3: 8.0


## 4. Building Models with Keras API
TensorFlow integrates with Keras for easy model building.

In [5]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

# Simple feedforward NN
model = Sequential([
    Dense(16, activation='relu', input_shape=(4,)),
    Dense(8, activation='relu'),
    Dense(3, activation='softmax')
])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 243 (972.00 B)

 Trainable params: 243 (972.00 B)

 Non-trainable params: 0 (0.00 B)

## 5. Training & Evaluation
You can compile and train models using `.compile()` and `.fit()`.

In [6]:
import numpy as np

# Dummy dataset
X = np.random.rand(100,4)
y = np.random.randint(0,3,100)

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X, y, epochs=5, batch_size=8, verbose=1)

Epoch 1/5
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.3887 - loss: 1.1207
Epoch 2/5
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3301 - loss: 1.1490 
Epoch 3/5
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3831 - loss: 1.0875 
Epoch 4/5
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3446 - loss: 1.1119 
Epoch 5/5
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3679 - loss: 1.1096 


## 6. Saving & Loading Models

In [7]:
model.save('my_model.h5')

# Load model
loaded_model = tf.keras.models.load_model('my_model.h5')
print('Model loaded successfully')

Model loaded successfully


## 7. TensorFlow Datasets (TFDS)
TensorFlow provides standard datasets for experiments.

In [8]:
import tensorflow_datasets as tfds

mnist = tfds.load('mnist', split='train', as_supervised=True)
for image, label in mnist.take(1):
    print('Image shape:', image.shape)
    print('Label:', label.numpy())

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist/incomplete.JXPV0B_3.0.1/mnist-train.tfrecord*...:   0%|          | 0…

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist/incomplete.JXPV0B_3.0.1/mnist-test.tfrecord*...:   0%|          | 0/…

Dataset mnist downloaded and prepared to /root/tensorflow_datasets/mnist/3.0.1. Subsequent calls will reuse this data.
Image shape: (28, 28, 1)
Label: 4


## 8. Practical Example: MNIST Classification

In [9]:
from tensorflow.keras.datasets import mnist

# Load data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize
x_train, x_test = x_train / 255.0, x_test / 255.0

# Build model
model = Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile & Train
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=3, validation_split=0.1)

# Evaluate
model.evaluate(x_test, y_test, verbose=2)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/3
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8739 - loss: 0.4472 - val_accuracy: 0.9627 - val_loss: 0.1350
Epoch 2/3
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9621 - loss: 0.1293 - val_accuracy: 0.9718 - val_loss: 0.0981
Epoch 3/3
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9756 - loss: 0.0824 - val_accuracy: 0.9755 - val_loss: 0.0894
313/313 - 1s - 2ms/step - accuracy: 0.9727 - loss: 0.0891


[0.08907367289066315, 0.9726999998092651]

# **Fin.**